version: "3"

services:
  web:
    build: .
    ports:
      - "3000:3000"
      # For debugging of the nodejs process
      - "9229:9229"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydatabase
    volumes:
      - ./src:/app/src

  db:
    ports:
      - "5432:5432"
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
